invert-whitelist: true

leaves:
  test-leaves:
    material: OAK_LEAVES
    distance: 4
    persistent: true
    item:
      material: PAPER
      name: "<green>Test Leaves"
      lore:
        - "<gray>This is a test item"
      glowing: true
    drops:
      requires-shears: true
      sapling:
        material: OAK_SAPLING
        name: "<green>Test Sapling"
        lore:
          - "<gray>This is a test sapling"
        glowing: true
      drops-self: true

logs:
  test-log:
    material: NOTE_BLOCK
    log-material: OAK_LOG
    instrument: BANJO
    powered: true
    item:
      material: Paper
      name: "<green>Test Logs"
      lore:
        - "<gray>This is a test item"
      glowing: false
  drops:
    requires-shears: false
    drops-self: true