name: HMCLeaves
version: "3.0.0-SNAPSHOT"
main: com.hibiscusmc.hmcleaves.paper.HMCLeavesPlugin
softdepend: [ Oraxen, ItemsAdder, MythicCrucible, Nova, WorldEdit, FastAsyncWorldEdit, ProtocolLib, ProtocolSupport, ViaVersion, ViaBackwards, ViaRewind, Geyser-Spigot ]
api-version: 1.20
load: STARTUP